### ISSUE TITLE
head link image not shown properly

### ISSUE THREAD

**Issue by jogee1994** [ahfarmer/emoji-search#10]
issue in this code - <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link **rel="shortcut icon"** href="./src/favicon.ico">
    <title>Emoji Search</title>
</head>

i think no need to add rel = "shortcut icon" here.

**Comment by ahfarmer** [comment]
Thanks for pointing this out! The fix was a little different though - needed to fix the href. Did that here:

https://github.com/ahfarmer/emoji-search/commit/1ddda8bf97cbbb791d13cb2ae3d4fb83e419f9f6
