### ISSUE TITLE
Project not opening

### ISSUE THREAD

**Issue by YashMaharshi** [ahfarmer/emoji-search#4]
hi,

I get an error : npm WARN deprecated wrench@1.5.8: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.

When I try to run " npm install " command

**Comment by ahfarmer** [comment]
Hey there, I just updated all the packages to the latest version. Want to give it another try @YashMaharshi ? Please comment if it is still not working and I'll re-open the issue.
