### ISSUE TITLE
How about adding copy to clipboard feature, when user clicks on any emoji.

### ISSUE THREAD

**Issue by rabingaire** [ahfarmer/emoji-search#6]

**Comment by ahfarmer** [comment]
Good idea! Do you want to add this?

**Comment by rabingaire** [comment]
I would love to. I will try to do it in few weeks.

**Comment by ahfarmer** [comment]
Added with https://github.com/ahfarmer/emoji-search/pull/9

Thanks @rabingaire ! Working great.
