### ISSUE TITLE
encountered two children with the same key

### ISSUE THREAD

**Issue by alirezavalizade** [ahfarmer/emoji-search#7]
Try type `mm`!

<img width="1440" alt="screen shot 2018-02-05 at 10 07 36 pm" src="https://user-images.githubusercontent.com/14992757/35822340-3c08beba-0ac1-11e8-9ffe-4fb2f518a4f7.png">

**Comment by ahfarmer** [comment]
Thanks! fixed with https://github.com/ahfarmer/emoji-search/pull/5
